import {db} from 'hatchable'; import {membership,cleanText} from 'lib/context.js';
export const access='user'; export const methods=['POST'];
const defs={home:'Reviewing Draft Books',daybook:'Reviewing Daybook',pos:'Ingesting POS activity',bank:'Matching bank transactions',ap:'Reviewing bills and checks',delivery:'Reconciling delivery payouts',payroll:'Processing payroll workspace',inventory:'Checking inventory variances',reports:'Refreshing draft reports',compliance:'Checking tax deadlines',scanner:'Reviewing source documents',reconcile:'Reconciling Draft Books',settings:'Reviewing workspace settings'};
const aliases={payroll:['payroll','pay run','wages'],bank:['bank','bank feed','transactions'],compliance:['compliance','tax deadline','calendar','filing'],pos:['pos','toast','clover','square','sales import'],ap:['a/p','accounts payable','bills','checks','vendor invoice'],delivery:['delivery','doordash','ubereats','grubhub'],inventory:['inventory','physical count','variance'],reports:['report','p&l','profit and loss','balance sheet'],scanner:['invoice scanner','scan invoice','receipt','document'],reconcile:['reconcile','reconciliation'],daybook:['daybook','journal','daily sales'],settings:['settings','chart of accounts','roles']};
function queue(prompt,active){const q=String(prompt||'').toLowerCase(),hits=[];for(const [module,words] of Object.entries(aliases)){let at=Infinity;for(const w of words){const i=q.indexOf(w);if(i>=0&&i<at)at=i}if(at<Infinity)hits.push({module,at})}hits.sort((a,b)=>a.at-b.at);let out=[...new Set(hits.map(x=>x.module))];if(out.includes('bank')&&/reconcil.{0,24}bank/.test(q))out=out.filter(x=>x!=='reconcile');return out.length?out:[defs[active]?active:'home']}
async function scope(user,businessId,locationId){await membership(user.id,businessId);const l=(await db.query('SELECT id FROM locations WHERE id=$1 AND business_id=$2 AND active=true',[locationId,businessId])).rows[0];if(!l)throw new Error('Location access denied')}
export default async function(req,res){try{const b=req.body||{},action=b.action,businessId=Number(b.business_id),locationId=Number(b.location_id);await scope(req.user,businessId,locationId);
if(action==='start'){const modules=queue(b.prompt,b.active_module);const r=await db.query("INSERT INTO copilot_runs(business_id,location_id,user_id,prompt,total_steps) VALUES($1,$2,$3,$4,$5) RETURNING id",[businessId,locationId,req.user.id,cleanText(b.prompt,3000),modules.length]);const runId=r.rows[0].id;for(let i=0;i<modules.length;i++)await db.query('INSERT INTO copilot_run_steps(run_id,position,module,title) VALUES($1,$2,$3,$4)',[runId,i+1,modules[i],defs[modules[i]]]);return res.status(201).json({run_id:runId,steps:modules.map((module,i)=>({position:i+1,module,title:defs[module],status:'queued'}))})}
const run=(await db.query('SELECT * FROM copilot_runs WHERE id=$1 AND business_id=$2 AND location_id=$3 AND user_id=$4',[Number(b.run_id),businessId,locationId,req.user.id])).rows[0];if(!run)return res.status(404).json({error:'Run not found'});
if(action==='step'){const position=Number(b.position),step=(await db.query('SELECT * FROM copilot_run_steps WHERE run_id=$1 AND position=$2',[run.id,position])).rows[0];if(!step)throw new Error('Run step not found');await db.query("UPDATE copilot_runs SET status='running',current_step=$1 WHERE id=$2",[position,run.id]);await db.query("UPDATE copilot_run_steps SET status='running',started_at=now() WHERE id=$1",[step.id]);const staged=(await db.query("SELECT count(*)::int count,COALESCE(sum(amount),0) total FROM staged_transactions WHERE business_id=$1 AND location_id=$2 AND status NOT IN('committed','rejected')",[businessId,locationId])).rows[0];const result={message:defs[step.module]+' complete. '+staged.count+' open Draft item(s) totaling '+Number(staged.total).toFixed(2)+' were available for review.',staged_count:staged.count,staged_total:Number(staged.total),module:step.module};await db.query("UPDATE copilot_run_steps SET status='completed',result=$1::jsonb,completed_at=now() WHERE id=$2",[JSON.stringify(result),step.id]);if(position===run.total_steps)await db.query("UPDATE copilot_runs SET status='completed',completed_at=now() WHERE id=$1",[run.id]);return res.json({step:{position,module:step.module,title:step.title,status:'completed',result}})}
if(action==='summary'){const generated=(await db.query("SELECT id,status,amount FROM staged_transactions WHERE copilot_run_id=$1 ORDER BY id",[run.id])).rows;const staged={count:generated.length,total:generated.reduce((n,x)=>n+Number(x.amount),0),approved:generated.filter(x=>x.status==='approved').length,ids:generated.map(x=>x.id)};const open=(await db.query("SELECT count(*)::int count,COALESCE(sum(amount),0) total FROM staged_transactions WHERE business_id=$1 AND location_id=$2 AND status NOT IN('committed','rejected')",[businessId,locationId])).rows[0];const steps=(await db.query('SELECT position,module,title,status,result FROM copilot_run_steps WHERE run_id=$1 ORDER BY position',[run.id])).rows;return res.json({run_id:run.id,status:run.status,steps,generated:{count:staged.count,total:Number(staged.total),approved:staged.approved,ids:staged.ids},draft_open:{count:open.count,total:Number(open.total)}})}
res.status(400).json({error:'Unknown action'})}catch(e){res.status(400).json({error:e.message})}}